export enum TipoResolucion {
  DESCARTADA = 'DESCARTADA',
  PUBLICACION_PAUSADA = 'PUBLICACION_PAUSADA',
  PUBLICACION_ELIMINADA = 'PUBLICACION_ELIMINADA',
  USUARIO_BLOQUEADO = 'USUARIO_BLOQUEADO',
}
