export enum TipoNotificacion {
  SOLICITUD_CREADA = 'SOLICITUD_CREADA',
  SOLICITUD_ACEPTADA = 'SOLICITUD_ACEPTADA',
  SOLICITUD_RECHAZADA = 'SOLICITUD_RECHAZADA',
  SOLICITUD_ACEPTADA_CANCELADA = 'SOLICITUD_ACEPTADA_CANCELADA',
  DENUNCIA_RESUELTA = 'DENUNCIA_RESUELTA',
  PUBLICACION_PAUSADA = 'PUBLICACION_PAUSADA',
  PUBLICACION_ELIMINADA = 'PUBLICACION_ELIMINADA',
  USUARIO_BLOQUEADO = 'USUARIO_BLOQUEADO',
}
